"""The thirty-page manuscript is the assembler's output, byte for byte.

`paper/general_formula/main.tex` is generated by `cut30/assemble.py` from the
base commit's text (read from the repository's history), the plan's passages
and the reviewer's corrections; an edit of main.tex by hand, or a part whose
anchor no longer matches, is caught here. The assembler needs the base commit
in the local history; a shallow checkout without it skips the test.
"""

import importlib.util
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
CUT30 = ROOT / "paper" / "general_formula" / "cut30"
MAIN_TEX = ROOT / "paper" / "general_formula" / "main.tex"


def _base_commit_available() -> bool:
    spec_text = (CUT30 / "cut30_lib.py").read_text(encoding="utf-8")
    commit = spec_text.split('BASE_COMMIT = "')[1].split('"')[0]
    result = subprocess.run(
        ["git", "-C", str(ROOT), "cat-file", "-e", f"{commit}:paper/general_formula/main.tex"],
        capture_output=True,
    )
    return result.returncode == 0


def test_main_tex_is_the_assemblers_output() -> None:
    if not _base_commit_available():
        pytest.skip("the base commit of the assembly is not in this checkout's history")
    sys.path.insert(0, str(CUT30))
    try:
        spec = importlib.util.spec_from_file_location("cut30_assemble", CUT30 / "assemble.py")
        module = importlib.util.module_from_spec(spec)
        assert spec.loader is not None
        spec.loader.exec_module(module)
        built = module.build()
    finally:
        sys.path.remove(str(CUT30))
    assert built == MAIN_TEX.read_text(encoding="utf-8"), (
        "main.tex differs from cut30/assemble.py's output: run the assembler, do not edit main.tex by hand"
    )


def test_every_correction_is_applied_once() -> None:
    if not _base_commit_available():
        pytest.skip("the base commit of the assembly is not in this checkout's history")
    sys.path.insert(0, str(CUT30))
    try:
        import corrections  # noqa: PLC0415

        labels = [label for label, _, _ in corrections.CORRECTIONS]
    finally:
        sys.path.remove(str(CUT30))
        sys.modules.pop("corrections", None)
    assert len(labels) == len(set(labels)), "a correction's label is repeated"
    text = MAIN_TEX.read_text(encoding="utf-8")
    for _, old, new in corrections.CORRECTIONS:
        if new:
            assert " ".join(new.split()) in " ".join(text.split()), old[:60]
