"""The thirty-page manuscript is the assembler's output, byte for byte.

`paper/general_formula/main.tex` is generated by `cut30/assemble.py` from the
base commit's text (read from the repository's history), the plan's passages
and the reviewer's corrections; an edit of main.tex by hand, or a part whose
anchor no longer matches, is caught here. The assembler needs the base commit
in the local history; a shallow checkout without it skips the test.
"""

import importlib.util
import subprocess
import sys
from pathlib import Path

import pytest

ROOT = Path(__file__).resolve().parents[1]
CUT30 = ROOT / "paper" / "general_formula" / "cut30"
MAIN_TEX = ROOT / "paper" / "general_formula" / "main.tex"
SUPPLEMENT_TEX = ROOT / "paper" / "general_formula" / "supplement.tex"


def _base_commit_available() -> bool:
    spec_text = (CUT30 / "cut30_lib.py").read_text(encoding="utf-8")
    commit = spec_text.split('BASE_COMMIT = "')[1].split('"')[0]
    result = subprocess.run(
        ["git", "-C", str(ROOT), "cat-file", "-e", f"{commit}:paper/general_formula/main.tex"],
        capture_output=True,
    )
    return result.returncode == 0


def test_main_tex_is_the_assemblers_output() -> None:
    if not _base_commit_available():
        pytest.skip("the base commit of the assembly is not in this checkout's history")
    sys.path.insert(0, str(CUT30))
    try:
        spec = importlib.util.spec_from_file_location("cut30_assemble", CUT30 / "assemble.py")
        module = importlib.util.module_from_spec(spec)
        assert spec.loader is not None
        spec.loader.exec_module(module)
        built, supplement = module.build_all()
        assert built == MAIN_TEX.read_text(encoding="utf-8"), (
            "main.tex differs from cut30/assemble.py's output: run the assembler, do not edit main.tex by hand"
        )
        assert supplement == SUPPLEMENT_TEX.read_text(encoding="utf-8"), (
            "supplement.tex differs from cut30/assemble.py's output: run the assembler, do not edit it by hand"
        )
        _check_reorder(module)  # one more build here, not in a second test: the parts are files
    finally:
        sys.path.remove(str(CUT30))
        sys.modules.pop("reorder", None)
        sys.modules.pop("supplement", None)


def test_every_correction_has_its_own_label() -> None:
    """Each correction is named once; that every one applies exactly once is
    asserted by the build itself (cut30_lib.sub), which the test above runs.
    A later correction may rewrite text an earlier one inserted, so no
    correction's text is required to survive verbatim."""
    sys.path.insert(0, str(CUT30))
    try:
        import corrections  # noqa: PLC0415

        labels = [label for label, _, _ in corrections.CORRECTIONS]
    finally:
        sys.path.remove(str(CUT30))
        sys.modules.pop("corrections", None)
    assert len(labels) == len(set(labels)), "a correction's label is repeated"
    assert all(old for _, old, _ in corrections.CORRECTIONS), "a correction has an empty anchor"


def _check_reorder(module) -> None:
    """The six heads' order (cut30/reorder.py) moves text and rewrites nothing
    beyond the joins: every cut block of the unordered text stands verbatim
    and once in main.tex, every label is defined once, every reference
    resolves, and the references whose targets moved point at the new place."""
    import re  # noqa: PLC0415

    reorder = module.reorder
    supplement_module = module.supplement
    moved = reorder.reorder
    split = supplement_module.split
    try:
        reorder.reorder = lambda text: text
        supplement_module.split = lambda text: (text, "")
        unordered = module.build()
    finally:
        reorder.reorder = moved
        supplement_module.split = split
    blocks = {}
    rest = unordered
    for name in reorder.BLOCKS:
        blocks[name], rest = reorder.cut(rest, name)
    main = MAIN_TEX.read_text(encoding="utf-8")
    for name, text in blocks.items():
        body = text
        if name == "families_table":
            body = text[len(reorder.FAMILIES_HEADING) :]
        if name == "law":
            body = text[len(reorder.BLOCKS["law"][0]) :]
            body = body.replace(reorder.TRANSITION_HEADING, blocks["code"] + reorder.TRANSITION_HEADING)
            # the hand-worked update and the code went to the Supplementary Material (S6)
            i = body.index(supplement_module.HANDWORKED_START)
            j = body.index(supplement_module.CODE_HEADING)
            body = body[:i] + supplement_module.POINTERS["handworked"] + body[j:]
        # the conversion table, the ledger and the families table went to the Supplementary Material (S7 to S9)
        for label, table in (
            (supplement_module.CONVERSION_LABEL, "S7"),
            (supplement_module.LEDGER_LABEL, "S8"),
            (supplement_module.FAMILIES_LABEL, "S9"),
        ):
            if label in body:
                _, body = supplement_module.cut_table(body, label, table)
        rewrites = reorder.REFS + [(reorder.FAMILIES_APPENDIX_REF, reorder.FAMILIES_BELOW_REF)]
        for old, new in rewrites + supplement_module.REFERENCES:
            body = body.replace(old, new)
        if not body.strip():
            continue  # the block was one table, now whole in the supplement (checked below)
        assert main.count(body) == 1, f"the block {name} does not stand once and whole in main.tex"
    supplement = SUPPLEMENT_TEX.read_text(encoding="utf-8")
    assert "\\label{tab:summary}" in main and "\\label{tab:nature}" not in main
    for label in ("tab:conversion", "tab:ledger", "tab:families"):
        assert f"\\label{{{label}}}" not in main and supplement.count(f"\\label{{{label}}}") == 1
    assert supplement.index("\\label{app:register}") < supplement.index(
        "\\caption{\\label{tab:nature}"
    ), "the full register opens the Supplementary Material"
    labels = re.findall(r"\\label\{([^}]*)\}", main)
    assert len(labels) == len(set(labels)), "a label is defined twice"
    refs = set(re.findall(r"\\(?:eq)?ref\{([^}]*)\}", main))
    assert refs <= set(labels), f"unresolved references: {refs - set(labels)}"
    # the register's caption moved to the Supplementary Material, its references prefixed there
    both = main + supplement.replace("{main-", "{")
    for old, new in reorder.REFS:
        assert main.count(old) == 0 and both.count(new) == 1, (
            f"a moved reference is not in place: {new[:50]}"
        )
