"""Assemble the thirty-page manuscript (paper/general_formula/main.tex).

Run from anywhere: `python paper/general_formula/cut30/assemble.py`. The four
parts build their text from the base commit's manuscript (cut30_lib.BASE) and
the new passages of the thirty-page plan (PLAN.md); this script joins them,
applies the reviewer's corrections (corrections.py), keeps only the cited
references, places the references before the appendices as the owner's map
orders, and writes main.tex with its header. `build()` returns the text
without writing it; tests/test_paper_cut30.py holds main.tex to it.
"""

import re
import runpy
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import corrections  # noqa: E402  (the path above)
import records  # noqa: E402
import reorder  # noqa: E402

HEADER = """% The paper on the general formula, the thirty-page form (the owner's instruction
% of 2026-09-22, record 573, and his guiding statement: only the closed results,
% the forcing ledger as the spine, the distance between the explicit model and
% the description of nature stated; PLAN.md, the thirty-page plan). Generated by
% cut30/assemble.py from the base commit's text, the plan's new passages and the
% reviewer's corrections (cut30/corrections.py); edit the parts, not this file.
% Every formula is the derivation's (docs/DERIVATIONS_BEAM.md) with its section;
% every check a detector reading of the experiments register
% (docs/EXPERIMENTS.md); NUMBERS.md maps each number to its source. The long
% form is at c15c1174, the forty-page cut at b0d1ebf7. The sections stand in
% the six heads' order (cut30/reorder.py; the owner's approval of 2026-09-23),
% one paper in one document (his word of 2026-09-23, record 1244: "we have no
% supplement; there is only one paper") at 48 pages (his word of the same day):
% the records cut from it stand verbatim in records.tex (cut30/records.py).
"""


def _references(text: str, bib: str) -> str:
    """The bibliography's entries that `text` cites, in the bibliography's order."""
    # A citation with an optional argument, \cite[section 10]{key}, counts too.
    cited = {
        k.strip()
        for m in re.finditer(r"\\cite(?:\[[^\]]*\])?\{([^}]*)\}", text)
        for k in m.group(1).split(",")
    }
    items = re.split(r"(?=\\bibitem\{)", bib)
    head = items[0]
    entries = {
        re.match(r"\\bibitem\{([^}]*)\}", it).group(1): re.sub(
            r"\\end\{thebibliography\}.*", "", it, flags=re.S
        )
        for it in items[1:]
    }
    # An entry cited only from another kept entry (the archive behind a document) is kept too.
    while True:
        more = {
            k.strip()
            for key in cited
            if key in entries
            for m in re.finditer(r"\\cite(?:\[[^\]]*\])?\{([^}]*)\}", entries[key])
            for k in m.group(1).split(",")
        }
        if more <= cited:
            break
        cited |= more
    kept = [entries[key] for key in entries if key in cited]
    # the references at footnotesize (the owner's "cut" to 36, record 922; the Boss's order of 11:30Z)
    return "{\\footnotesize\n" + head + "".join(kept) + "\\end{thebibliography}}\n\n"


def build_all() -> tuple[str, str]:
    """(main.tex, records.tex): the four parts joined, corrected, reordered,
    the records cut out, the references filtered."""
    for i in (1, 2, 3, 4):
        runpy.run_path(str(HERE / f"part{i}.py"), run_name="__main__")
    parts = "".join((HERE / f"part{i}.tex").read_text() for i in (1, 2, 3, 4))
    for i in (1, 2, 3, 4):
        (HERE / f"part{i}.tex").unlink()
    s = (
        parts.replace("sec:newton", "sec:forces")
        .replace("Part~III", "Section~\\ref{sec:measurement}")
        .replace("Part~II", "Sections~\\ref{sec:forces} and~\\ref{sec:delay}")
        .replace("Part~I", "Section~\\ref{sec:law}")
    )
    s = corrections.apply(s)
    s = reorder.reorder(s)  # the six heads (the owner's approval of 2026-09-23)
    s, recs = records.cut(s)  # the records file (the owner's "48 pages", one paper)
    body = s[: s.index("\\begin{thebibliography}")]
    bib = s[s.index("\\begin{thebibliography}") :]
    i = body.index("\\appendix")
    # The references follow the body on its last page (the cut to 35 pages of
    # 2026-09-22, record 852); the page split is read from the page numbers.
    paper = HEADER + body[:i] + _references(body, bib) + body[i:] + "\\end{document}\n"
    return paper, records.RECORDS_HEADER + recs + "\n"


def build() -> str:
    """The manuscript's text (main.tex); `build_all` gives the records file beside it."""
    return build_all()[0]


def main() -> None:
    out, recs = build_all()
    (HERE.parent / "main.tex").write_text(out)
    (HERE.parent / "records.tex").write_text(recs)
    print("main.tex written; references kept:", out.count("\\bibitem{"))
    print("records.tex written:", len(recs), "characters")


if __name__ == "__main__":
    main()
