"""Assemble the thirty-page manuscript (paper/general_formula/main.tex).

Run from anywhere: `python paper/general_formula/cut30/assemble.py`. The four
parts build their text from the base commit's manuscript (cut30_lib.BASE) and
the new passages of the thirty-page plan (PLAN.md); this script joins them,
keeps only the cited references, places the references before the appendices
as the owner's map orders, and writes main.tex with its header.
"""
import re
import runpy
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

HEADER = """% The paper on the general formula, the thirty-page form (the owner's instruction
% of 2026-09-22, record 573, and his guiding statement: only the closed results,
% the forcing ledger as the spine, the distance between the explicit model and
% the description of nature stated; PLAN.md, the thirty-page plan). Generated by
% cut30/assemble.py from the base commit's text and the plan's new passages; edit
% the parts, not this file. Every formula is the derivation's
% (docs/DERIVATIONS_BEAM.md) with its section; every check a detector reading of
% the experiments register (docs/EXPERIMENTS.md); NUMBERS.md maps each number to
% its source. The long form is at c15c1174, the forty-page cut at b0d1ebf7.
"""


def main() -> None:
    for i in (1, 2, 3, 4):
        runpy.run_path(str(HERE / f"part{i}.py"), run_name="__main__")
    parts = "".join((HERE / f"part{i}.tex").read_text() for i in (1, 2, 3, 4))
    s = (parts.replace("sec:newton", "sec:forces")
         .replace("Part~III", "Section~\\ref{sec:measurement}")
         .replace("Part~II", "Sections~\\ref{sec:forces} and~\\ref{sec:delay}")
         .replace("Part~I", "Section~\\ref{sec:law}"))
    body = s[:s.index("\\begin{thebibliography}")]
    cited = {k.strip() for m in re.finditer(r"\\cite\{([^}]*)\}", body) for k in m.group(1).split(",")}
    bib = s[s.index("\\begin{thebibliography}"):]
    items = re.split(r"(?=\\bibitem\{)", bib)
    head, kept = items[0], []
    for it in items[1:]:
        key = re.match(r"\\bibitem\{([^}]*)\}", it).group(1)
        if key in cited:
            kept.append(re.sub(r"\\end\{thebibliography\}.*", "", it, flags=re.S))
    i = body.index("\\appendix")
    out = (HEADER + body[:i] + "{\\small\n" + head + "".join(kept)
           + "\\end{thebibliography}}\n\n" + body[i:] + "\\end{document}\n")
    (HERE.parent / "main.tex").write_text(out)
    for i in (1, 2, 3, 4):
        (HERE / f"part{i}.tex").unlink()
    print("main.tex written; references kept:", len(kept))


if __name__ == "__main__":
    main()
