"""The section on the massive record kind (the owner's words of 2026-09-23
and 2026-09-24: "everything starts from the algebra"; the Boss's storyline,
docs/designs/detector_law/PLAN.md section 8): the paper's statement of
docs/ALGEBRA.md chapter 8, in the paper's voice, placed by cut30/reorder.py
after the algebra's section and before the click-to-click chain. Every
sentence is the algebra document's with its mark (proved there, carried
from the design, or computed and not proved); no run enters; every number
is a COMPUTATION declared before any run.
"""

SECTION = r"""\section{The massive record kind: the pair per kind, the band, the cone and the block}\label{sec:massive}

The law of Section~\ref{sec:algebra} was written for records that hop whole; the law as it stands today gives every record kind one declared pair of integers and lets the same six operations carry mass, a clock and a body \cite[chapter 8]{algebra}. This section states that law as the algebra document states it, before any run: each sentence carries the document's mark, proved there for every grain and every board, carried from the design's proof \cite{massiverecord}, or computed and not proved; every number is a computation declared before its run \cite{closure,declarations}, and the runs that read them are Section~\ref{sec:comparison}'s.

\paragraph{The rule with a pair per kind.} At every Node a record's row $(a_{\mathrm{now}}, a_{\mathrm{before}}, r)$ is mapped once per interval by
\begin{equation}\label{eq:massive}
3\,\mathrm{den}\;a_{\mathrm{next}} + r' = \mathrm{num}\;S_6 - 3\,\mathrm{den}\;a_{\mathrm{before}} + r, \qquad 0 \le r' < 3\,\mathrm{den},
\end{equation}
$S_6$ the sum of the six neighbours' $a_{\mathrm{now}}$ (the Node itself on a folded axis, $0$ beyond an open face), then the shift $a_{\mathrm{before}} \leftarrow a_{\mathrm{now}}$, $a_{\mathrm{now}} \leftarrow a_{\mathrm{next}}$, $r \leftarrow r'$. Light is the value $[\mathrm{num}, \mathrm{den}] = [1, 1]$; a massive kind is a value $\mathrm{den} > \mathrm{num}$, and nothing else names the mass. The verbs are (B), one entry $\mathrm{num}$ of the declared matrix on the six reads and one entry $-3\,\mathrm{den}$ on the own row's past; (T), the accumulator translated by that rate; and (D), the division by the wall $3\,\mathrm{den}$ with the remainder kept on the row. The three tests hold: one primitive with one declared pair and no family name, light the value $\mathrm{num} = \mathrm{den}$; the three verbs on the row with no root and no float; the record's own row and its six reads, nothing kept at a Node beyond the row and its remainder.

\paragraph{The band and the pitch.} Read on a character $\cos(\omega t - \mathbf k\cdot\mathbf x)$ of a periodic board, Eq.~\eqref{eq:massive} without its remainder holds exactly when $2\cos\omega = (2\,\mathrm{num}/(3\,\mathrm{den}))(\cos k_x + \cos k_y + \cos k_z)$; with light's band $\cos\omega_l(\mathbf k) = (\cos k_x + \cos k_y + \cos k_z)/3$ at the same $\mathbf k$ the same line reads
\begin{equation}\label{eq:band}
\boxed{\,\cos\omega = \cos\omega_0\,\cos\omega_l(\mathbf k), \qquad \cos\omega_0 = \mathrm{num}/\mathrm{den}\,},
\end{equation}
the massive band as light's band times the pitch's cosine, proved in the algebra document for every grain and every periodic board. At $\mathbf k = 0$ the gap is the pitch $\omega_0$, the rest period $N_0 = 2\pi/\omega_0$ intervals, the rest energy $h\omega_0$, de Broglie's internal clock as the thing compared with; light has $\omega_0 = 0$, a zero mode that is a level and not a clock, so the whole difference between light and a massive record in the algebra is a gap. With $2 - 2\cos\omega = 4\sin^2(\omega/2)$ the band is light's form with the pace squared scaled by $\mathrm{num}/\mathrm{den}$, one substitution.

\paragraph{The two paces and the exact cone.} Near $\mathbf k = 0$ light's band gives $\omega_l^2 = k^2/3 + O(k^4)$, the pace $c = 1/\sqrt3$ of Section~\ref{sec:geometry} reached once more. To second order in $\omega$ and $\mathbf k$ together the massive band is Klein--Gordon's with the cone $c_m^2 = \cos\omega_0\,c^2$, a massive record's limiting pace below light's by $\omega_0^2/4$ ($0.39$ percent at $N_0 = 50$, COMPUTATION); with no truncation in $\omega_0$, at the band's bottom,
\begin{equation}\label{eq:cone}
\boxed{\,\omega^2 = \omega_0^2 + c_{\mathrm{eff}}^2\,k^2 + O(k^4), \qquad c_{\mathrm{eff}}^2 = \cos\omega_0\,\frac{\omega_0}{\sin\omega_0}\,c^2, \qquad \frac{c_{\mathrm{eff}}^2}{c_m^2} = \frac{\omega_0}{\sin\omega_0} = 1 + \frac{\omega_0^2}{6} + O(\omega_0^4)\,},
\end{equation}
proved in the algebra document as the expansion at the band's bottom ($1.0037$ at the pitch $\mu = 0.15$, COMPUTATION). So a bound clock in motion dilates by $\gamma_m = 1/\sqrt{1 - v^2/c_{\mathrm{eff}}^2}$ at the massive kind's own cone and not by $\gamma = 1/\sqrt{1 - v^2/c^2}$ at light's: two gammas, apart by about $\beta^2\gamma^2\omega_0^2/4$ to second order, the lattice's own signature (Section~\ref{sec:comparison}).

\paragraph{Light against itself.} Light's own band, the pair $[1, 1]$, disperses by wavelength and by direction with nothing declared: along a unit direction $\mathbf n$ with $|\mathbf k| = k$,
\begin{equation}\label{eq:dispersion}
\boxed{\,\frac{v_g}{c} = 1 - \frac{\bigl(3\sum_i n_i^4 - 1\bigr)\,k^2}{24} + O(k^4)\,},
\end{equation}
the coefficient $0$ on a body diagonal, $1/2$ on a face diagonal, $2$ on an axis and $4/5$ averaged over the sphere (COMPUTATION, the series checked against the exact group pace \cite{lightdispersion}): a prediction of the form, the quadratic dispersion of light anisotropic on the sky with a cubic pattern and no free coefficient, its falsifier a set of bursts in different directions whose dispersion coefficients do not fit one cubic pattern once nature's sensitivity reaches the effect; nature today has bounds and no measured coefficient (row A2 of Section~\ref{sec:comparison}).

\paragraph{The block: the foreign object on the board.} A body is no new group object and no new verb: a finite set $R$ of Nodes closed under the cube's symmetries (a cube; a square on a layer), declared as world data like a wall's placement; the rule of Eq.~\eqref{eq:massive} on $R$ with a lowered pair $[\mathrm{num}', \mathrm{den}']$, $\mathrm{num}'/\mathrm{den}' > \mathrm{num}/\mathrm{den}$, a well of the pair in the medium whose own pair is the kind's declaration, the medium's pitch $\mu$; its clock the bound mode of the map in that well, $\omega_b$, a character of the time translation at $\mathbf k = 0$, one element of $\Z[\Z_{\Nphi}]$ carried by all the cells in step; its motion the characters of the band's surface; its momentum the existing $\mathbf p$ in $\Z^3$ and its step the existing verb (T), one integer per axis for the whole block with its remainder; its push the stress of light's field at its outer Ports; its click the evaluation across $R$. Nothing is declared in motion: the mode's extent, frequency and regime follow from the pair and the side. The block is no element of the phase circle: its place is in the symmetry group of the cube, the shape of its cells on the board, and its action is on the phase circle, through its table, a shift $t$ of the record's phase applied in the linear form to the record's pair of levels by verb (B), one division per output, no reading of a phase and no register at a Node \cite[section 14]{declarations}; what runs on the circle is the record's phase, as for every record. Two regimes by the side $s$ against the one-Node extent: the well, $s$ small, the mode extending beyond the cells, its clock in motion Lorentz's to first order; the cavity, $s$ comparable or larger, the mode inside the cells, its clock in motion the medium's. These are the cubes placed on the GameBoard that stand for the external bodies of an experiment, and every experiment of Section~\ref{sec:comparison} is a world file of such blocks, lamps and detectors.

\paragraph{The motion, one formula and its two limits.} The moving block is a resting block of width $\gamma_m s$ along its motion with the same well, read at $1/\gamma_m$:
\begin{equation}\label{eq:motion}
\frac{f}{f_0} = \frac{\omega_b(\gamma_m s, g_w)}{\gamma_m\,\omega_b(s, g_w)}, \qquad \gamma_m = \frac{1}{\sqrt{1 - v^2/c_{\mathrm{eff}}^2}},
\end{equation}
$f_0$ the rest clock's frequency and $f$ the moving one's, both a count between clicks on the block's own record, $\omega_b(s, g_w)$ the lowest mode of the well of side $s$ and depth $g_w$ on the world's own board, a computation per world before its run. The design derives it as the boost of the continuum operator of the band's bottom: the declared cells widen in the block's frame and never contract, and Lorentz is reached as a relation on the characters, no boost being among the $48$. On the GameBoard the formula is computed and not proved (to $0.01$ percent for $s \ge 12$ on a chain, $0.15$ percent on a layer). Its two limits are identities of the formula: in the well limit $f/f_0 \to 1/\gamma_m$, Lorentz's clock as the thing compared with; in the cavity limit $f/f_0 \to 1/\gamma_m^2$, the medium's clock; between them the first-order deviation is $\epsilon(\gamma_m^2 - 1)/2$ below $1/\gamma_m$, $\epsilon$ the mode's binding depth, the carried cells' mark on a bound clock and a prediction. Row 4a's number is this formula at the exact cone on its declared layer world, $0.8116$, with $0.8108$ at $c_m$ and $0.8132$ at $c$ beside it as controls (COMPUTATION \cite{closure}).

\paragraph{The coupling of the two kinds.} At a cell of $R$ the two records' rows are coupled by one entry of verb (B)'s declared matrix over the other record's two columns, the first difference both ways: the massive row gains $g\,(a_{l,\mathrm{now}} - a_{l,\mathrm{before}})$, the receive, and light's row gains $-G\,(a_{m,\mathrm{next}} - a_{m,\mathrm{now}})$, the source, both local to the cell. The scheme is the Euler--Lagrange scheme of a two-point Lagrangian, so it is symplectic and has an exact quadratic invariant $J$, proved in the algebra document for every board (exact to $10^{-12}$ on a chain, COMPUTATION); the amplitude form of the coupling is withdrawn as tachyonic, its mass matrix at $\mathbf k = 0$ having a negative eigenvalue. The block emits at its mode through the same entry, a lamp at its own rest frequency, and a medium block at rest has the index $n^2 = 1 + Gg/(\omega_0^2 - \omega^2)$ in closed form, a control of the coupling with the cavity's own mode sum beside it and the $4$ percent between them open in size.

\paragraph{The detector and the click.} A detector is not an element of either group: it is a declared set of Nodes with a rung $W$, and it counts when the quadratic form of the record's values in its cells crosses $W$, the comparison $W \times (\text{the pointer}) \ge (\text{the record's norm})$, integers both, the evaluation (E) of the record on the cells in the detector's own clock. A body is a detector of itself, across its own cells; a light detector is a Node or a line of Nodes with a rung on the light record. Light is read by moving the record at the detector's cells, and the detector clicks; the verbs are lossless and the click needs no sink. One click per record, and the record's completion, one gather over all its detectors, is the only non-local step; nothing else leaves the Inside. Where a world must absorb it declares a take, a damping pair on light's row at the cells of an absorbing object, a declaration of the world and not the law's. What is a measurement stays the reading rule of Section~\ref{sec:click}.

\paragraph{The direction of time.} Given the neighbours' reads, the step $(a_{\mathrm{before}}, r) \mapsto (a_{\mathrm{next}}, r')$ of one row is a bijection of $\Z \times \{0, \dots, d - 1\}$ onto itself, by the uniqueness of the Euclidean division, with an exact inverse, the ceiling in place of the floor, a declared variant of the one division: the Inside is reversible to the bit for every grain and every board, and not symmetric in form, the remainder living on the later level. The click is the one deletion of the law, and the evaluation $\mathrm{ev}$ with the weight and the rung is many-to-one at every step: the arrow of time is born at the click, and at a declared take, and nowhere in the rule. The world that shows it is a check and never a pin: a train with no detector run forward and back under the exact inverse returns to its first rows bit for bit, and the same world with a detector does not, by the deleted rows exactly.

\paragraph{Known formulas and predictions.} Every row of Section~\ref{sec:comparison} carries (K), a known-formula row, the algebra's identity a textbook formula as the thing compared with and the engine reaching it the control of the engine against the algebra, or (P), a prediction row, a number the algebra gives and no known formula gives; a prediction is not a pass. The eight predictions of the massive kind, each declared before any run with its falsifier in the algebra document \cite[8.9]{algebra}: the two-pace world, a massive record's limiting pace $c_m$ below $c$ by $\omega_0^2/4$ and its bound clock at $c_{\mathrm{eff}}$; the bound clock's second term $\epsilon(\gamma_m^2 - 1)/2$; the index in motion; the hop's parametric pump; the two arms held by light alone; the atom's lines at the coupled modes' own frequencies; the click's arrow of time; and the light clock of two bodies, $N_0 = 2L/c$ plus the two ring-ups.

"""
